name: Multip
description: The adapter will report the body of a successful GET request to the specified get, or return an error if the response status code is greater than or equal to 400.
node_identifier: blueoracle
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: Chainlink
    url: https://docs.chain.link/docs/adapters
parameters:
  - base
  - quote
